language: java

sudo: required

services:
  - docker

jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "taizel-github"

script:
  - mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
